### PR TITLE
ObservableFactoryWrapper should convert promise to observable

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by asm89** [comment]
Good catch! Could you add a test for this?

**Comment by WyriHaximus** [comment]
@asm89 Will do! Just need to find where 😂

**Comment by WyriHaximus** [comment]
Hmmm no existing test, will create a new one 👍

**Comment by asm89** [comment]
@WyriHaximus I think this is mostly tested indirectly through operators that take a selector. I'd consider adding a test to one of those that covers this case.

**Comment by WyriHaximus** [comment]
@asm89 Just added tests for the whole class directly

**Comment by asm89** [comment]
Thanks for the extra tests!

**Comment by WyriHaximus** [comment]
No problem! :+1:

**Pull request merged**
