### PR TITLE
Custom operator in nested namespace

### PR DESCRIPTION
**Pull request by mamciek**
Allow customer operators in namespace like: \Vendor\Sub\Sub\Rx\Operator

### CODE REVIEW

**Comment by mamciek** [comment]
Added test.

**Comment by mamciek** [comment]
Does anybody knows why Travis HHVM build does not pass? It fails with different demo/test.php every time.

**Comment by mbonneau** [comment]
The HHVM fails intermittently on the 1.x (current master) branch. This is due to timing issues.

I have restarted the build.

**Comment by davidwdan** [comment]
Maybe we should move HHVM to allow failures

**Comment by mamciek** [comment]
@davidwdan I have added test. Is it ready to merge in your opinion?

**Pull request merged**
