### PR TITLE
compose() operator

### PR DESCRIPTION
**Pull request by mamciek**
Please add thru() operator inspired by mostjs: https://github.com/cujojs/most/blob/master/docs/api.md#thru

```php
$process = function ($observable) {
    return $observable
        ->filter(function ($val) { return $val % 2 == 0; })
        ->map(function ($val) { return $val * 2; });
};
```

it allows to use

```php
$source = Observable::fromArray(range(1, 10))
       ->map(..)
       ->filter(..)
        ->thru($process)
        ->map(..);

```

instead of
```php
$source = $process(
                    Observable::fromArray(range(1, 10))
                       ->map(..)
                       ->filter(..)
                  )->map(..);
```

### CODE REVIEW

**Comment by martinsik** [comment]
@mamciek I think you could write the same with `concatMap`:
```
Observable::fromArray(range(1, 10))
    ->concatMap(function($value) use ($process) {
        return $process(Observable::of($value));
    });
```

**Comment by davidwdan** [comment]
Is this similar to RxJava's `compose` operator? I think that this operator can be useful for cleaning up code and is worth adding.

@mamciek can you add some tests?

**Comment by mamciek** [comment]
I will add some tests. I wasn't aware of `compose` operator from RxJava. I only knew about `thru` in mostjs. I personaly think that `thru` is much better name, but maybe I should rename to `compose` in order to be more "compatible" with Rx family?

**Comment by ddimaria** [comment]
+1 for compose as it has explicit meaning to FP programmers

**Comment by asm89** [comment]
+1 for being more compatible with naming in the Rx family

**Pull request merged**
