### PR TITLE
PHP 8.2 compatibility

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Interesting, I mainly started working on this PR to deal with dynamic properties being deprecated in PHP 8.2. But the test don't show any of that...

**Comment by WyriHaximus** [comment]
Found the error again in a gist and push the fix in the last commit. It fixes the following error:

```
Deprecated: Creation of dynamic property Rx\Scheduler\ScheduledItem::$disposable is deprecated in /opt/app/vendor/reactivex/rxphp/src/Scheduler/ScheduledItem.php on line 26      
```

**Comment by WyriHaximus** [comment]
@mbonneau This is now ready for review. What bothers me most is that this error doesn't come up during tests

**Comment by mbonneau** [comment]
@WyriHaximus Thanks! I will check this out this weekend hopefully.

**Pull request merged**
