### PR TITLE
Fix for changing yield behavior in hhvm

### PR DESCRIPTION
**Pull request by robations**
A possible fix. Version comparison has been taken outside the anon function to simplify the IF logic, and avoid re-comparing inside a loop. I've not read any submission guidelines so this is mainly provided as a discussion point!

### CODE REVIEW

**Comment by davidwdan** [comment]
Do we know if the behavior in v3.11 is the expected behavior for HHVM, or will it switch back at some point?

**Comment by robations** [comment]
Good question. After searching around I think this is the best clue:

https://github.com/facebook/hhvm/issues/1871

This discusses the issue with `next()` and suggests this was fixed in 3.11 when addressing PHP7 compatibility. The 3v4l.org links at the bottom show the same behaviour carrying through to 3.12.

**Comment by asm89** [comment]
lgtm :+1:

**Comment by davidwdan** [comment]
@robations I'm going to merge this as is.  If we need to refactor it, we can do that at a later date.

**Comment by robations** [comment]
Okay great, I did think of another way to cut this but as you say can be reworked later :)

**Pull request merged**
