### PR TITLE
Map updates

### PR DESCRIPTION
**Pull request by davidwdan**
Added index to `map` selector
Added `mapTo` operator
Fixed bug where the `map` operator called `onNext` after it was disposed

### CODE REVIEW

**Comment by asm89** [comment]
Can we add `mapWithIndex()` and have an explicit operator for it? I think there are plenty of cases where you'd want to map without the index, so I'd rather make it explicit for the cases where you want to have the index (in that case it probably makes sense to make the index the first argument?).

`mapWithIndex()` will potentially have problems with `$index` growing over `PHP_INT_MAX`.

**Comment by davidwdan** [comment]
Yeah, that makes sense.

**Comment by asm89** [comment]
@davidwdan Now I think of it, we don't even need the explicit operator, we should just write `mapWithIndex` in terms of `map()`. E.g.

```
public function mapWithIndex(callable $selector)
{
    $index = 0;
    return $this->map(function($value) use ($selector, &$index) {
        return call_user_func_array($selector, [$index++, $value]);
    });
}
```

That should work?

**Comment by asm89** [comment]
:+1:

**Pull request merged**
